#!/bin/bash

# Перейти в директорию вашего проекта
cd /root/project/Assistant

# Пуллить последние изменения из репозитория
git pull

# Устанавливаем зависимости
pip install --upgrade pip
pip install -r requirements.txt

# Перезапустить службу бота
sudo systemctl restart bot_service

